version: "3.8"

services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  dashboard:
    build: .
    container_name: dashboard
    depends_on:
      - mongodb
      - importer
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/dashboard
      - PORT=8000

  importer:
    build: .
    container_name: importer
    depends_on:
      - mongodb
    # запускаем импорт и сразу выходим
    command: ["python", "import_data.py", "--mongo-uri", "mongodb://mongodb:27017/dashboard"]
    # импорт данных не должен оставаться долго в фоне
    restart: "no"

volumes:
  mongo-data:
