version: '3.8'
services:
  mongodb:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  api:
    build: .
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/dashboard
    ports:
      - "8000:8000"

volumes:
  mongo-data:
